"""Initial tables

Revision ID: 412c4a9201df
Revises: 
Create Date: 2025-07-27 22:58:17.503692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412c4a9201df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('landlord', 'tenant'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'terminated'), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('payment_interval', sa.Enum('monthly', 'weekly'), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing')
    op.drop_table('agreement')
    op.drop_table('user')
    # ### end Alembic commands ###
